### PR TITLE
Tenants

### PR DESCRIPTION
**Pull request by PierreZ**
Adding support for [tenants](https://apple.github.io/foundationdb/tenants.html).

### CODE REVIEW

**Comment by PierreZ** [comment]
Blocked by #31 because Tenant management functions are expected to run inside a [db.run](https://github.com/apple/foundationdb/blob/1e8225a19eb5fc11950fd150469b89181248bcd4/bindings/java/src/main/com/apple/foundationdb/TenantManagement.java)

**Comment by Speedy37** [comment]
Good start.
I think a `TenantDatabase` type with `create_trx`, `run` and `transact*` methods could be nice.

**Comment by PierreZ** [comment]
> Good start. I think a `TenantDatabase` type with `create_trx`, `run` and `transact*` methods could be nice.

I agree :smile: Currently focusing on the `bindingTester`, but that should be next :rocket:

**Comment by PierreZ** [comment]
I have started some work with another pr because I think something is wrong on bindingTester.

**Comment by PierreZ** [comment]
Blocked by bindingTester issue. More details [here](https://forums.foundationdb.org/t/binding-tester-heisenbug-with-api-version-710-and-tenant/3306/13)

**Comment by PierreZ** [comment]
Given `tenant` are highly experimental and won't be stable in a short-term, I propose that:

* we add more warning about the state of tenants in fdb,
* we allow failure on bindingTester when running it with tenant enabled.

Like this, we will be able to merge this work

**Comment by Speedy37** [comment]
Maybe put it behind a feature flag.

**Comment by PierreZ** [comment]
> Maybe put it behind a feature flag.

Sorry for the late reply, i was busy on other subject. You are right, I will do that, once I'm back from holiday 🎄

**Comment by PierreZ** [comment]
Ready to be reviewed.

We have used the tenant's feature internally in Clever Cloud, so things are working as expected. 

Please bare in mind that this is an experimental feature

**Pull request merged**
